version: "3.5"
services:
  linkwarden:
    build: .
    environment:
      - NEXTAUTH_URL=https://${SPACE_ID}.hf.space/api/v1/auth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - HF_TOKEN=${HF_TOKEN}
      - DATASET_ID=${DATASET_ID}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-7200}
      - SPACE_ID=${SPACE_ID}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data 