version: "3.5"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  linkwarden:
    build: .
    environment:
      - NEXTAUTH_URL=https://${SPACE_ID}.hf.space/api/v1/auth
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - HF_TOKEN=${HF_TOKEN}
      - DATASET_ID=${DATASET_ID}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-7200}
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
